### PR TITLE
Fix for ffi #119 and move to rust 1.49

### LINKED ISSUE #119: Build error on bare system - building from source
## Describe the bug?

Trying to build the repo from source throws errors about SSE support. Here is the error in its entirety:

## Steps to reproduce?
1. git clone https://github.com/capsule-rs/capsule.git
2. cargo build

## Expected behavior?

Successful build

### Capsule version?

Git

### OS?

Ubuntu 18.10

### Docker / VM / Bare?

Bare

### Stack trace or error log output

`  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-march=corei7" "-o" "/users/deep83/rust/capsule/target/debug/build/capsule-ffi-9f389138f8a5f94a/out/src/shim.o" "-c" "src/shim.c"
  cargo:warning=In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
  cargo:warning=                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/x86intrin.h:48,
  cargo:warning=                 from /usr/local/include/rte_vect.h:28,
  cargo:warning=                 from /usr/local/include/rte_memcpy.h:17,
  cargo:warning=                 from /usr/local/include/rte_ether.h:21,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h: In function ‘rte_mov32’:
  cargo:warning=/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:926:1: error: inlining failed in call to always_inline ‘_mm256_storeu_si256’: target specific option mismatch
  cargo:warning= _mm256_storeu_si256 (__m256i_u *__P, __m256i __A)
  cargo:warning= ^~~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/local/include/rte_ether.h:21:0,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h:321:2: note: called from here
  cargo:warning=  _mm256_storeu_si256((__m256i *)dst, ymm0);
  cargo:warning=  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
  cargo:warning=                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/x86intrin.h:48,
  cargo:warning=                 from /usr/local/include/rte_vect.h:28,
  cargo:warning=                 from /usr/local/include/rte_memcpy.h:17,
  cargo:warning=                 from /usr/local/include/rte_ether.h:21,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:920:1: error: inlining failed in call to always_inline ‘_mm256_loadu_si256’: target specific option mismatch
  cargo:warning= _mm256_loadu_si256 (__m256i_u const *__P)
  cargo:warning= ^~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/local/include/rte_ether.h:21:0,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h:320:7: note: called from here
  cargo:warning=  ymm0 = _mm256_loadu_si256((const __m256i *)src);
  cargo:warning=  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  exit code: 1

  --- stderr

  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-march=corei7" "-o" "/users/deep83/rust/capsule/target/debug/build/capsule-ffi-9f389138f8a5f94a/out/src/shim.o" "-c" "src/shim.c" with args "cc" did not execute successfully (status code exit code: 1).`

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
## Description

- Fixes #119 with changes to meson/clang
- Move to Rust 1.49
  * assoc clippy changes
- Test/move to Dpdk 19.11.6
  * updated pcap open_dump doesn't err on empty file, so check for first

- Associated PR on sandbox: https://github.com/capsule-rs/sandbox/pull/21

## Type of change

- [X] Bug fix
- [X] Documentation update

## Checklist

- [X] Associated tests (ran)
- [X] Associated documentation for Rust 1.49

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
@drunkirishcoder I'm seeing a sanitizer error on CI, but not locally on the VM and my local system76 (bare). The EAL/bad descriptor logs were always there (possibly due to NUMA), but we never got this type of leak (below). I even tried a rust version of nightly that ran 20 days ago (and passed), but same error. I thought it could be the move from DPDK 19.11.1 -> 19.11.6, but I couldn't reproduce locally on both tries. Can you investigate and make sure it's only on CI (crazy azure kernel!)? 

```
=================================================================
==1==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 14800 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bec4f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d404c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h92f11991e564882e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e02a06b in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:429:20
    #7 0x55dd7df78fab in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 14800 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bec4f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d404c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h92f11991e564882e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e02a01d in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:428:19
    #7 0x55dd7df78fab in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 14800 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac9b2 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x55dd7e11e4ae in alloc::alloc::alloc_zeroed::ha0b2282220cb6b70 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:155:14
    #2 0x55dd7e11ed9f in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:43
    #3 0x55dd7e122a2e in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::ha915ea78757e6f79 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:231:9
    #4 0x55dd7e0bebbf in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:189:38
    #5 0x55dd7e0d5c3c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::h1c7f813946ef038c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:136:9
    #6 0x55dd7e158beb in alloc::vec::from_elem::h7e7e6738858c5994 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7e02a06b in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:429:20
    #8 0x55dd7df78fab in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #9 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #10 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #11 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #12 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #13 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #14 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #15 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #16 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #17 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #18 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #19 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #20 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #21 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #22 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #23 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #24 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #25 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 14800 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac9b2 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x55dd7e11e4ae in alloc::alloc::alloc_zeroed::ha0b2282220cb6b70 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:155:14
    #2 0x55dd7e11ed9f in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:43
    #3 0x55dd7e122a2e in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::ha915ea78757e6f79 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:231:9
    #4 0x55dd7e0bebbf in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:189:38
    #5 0x55dd7e0d5c3c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::h1c7f813946ef038c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:136:9
    #6 0x55dd7e158beb in alloc::vec::from_elem::h7e7e6738858c5994 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7e02a01d in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:428:19
    #8 0x55dd7df78fab in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #9 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #10 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #11 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #12 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #13 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #14 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #15 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #16 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #17 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #18 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #19 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #20 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #21 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #22 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #23 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #24 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #25 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 13704 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bec4f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d404c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h92f11991e564882e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e02a06b in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:429:20
    #7 0x55dd7df78ffb in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1523:26
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 13704 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac9b2 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x55dd7e11e4ae in alloc::alloc::alloc_zeroed::ha0b2282220cb6b70 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:155:14
    #2 0x55dd7e11ed9f in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:43
    #3 0x55dd7e122a2e in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::ha915ea78757e6f79 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:231:9
    #4 0x55dd7e0bebbf in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:189:38
    #5 0x55dd7e0d5c3c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::h1c7f813946ef038c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:136:9
    #6 0x55dd7e158beb in alloc::vec::from_elem::h7e7e6738858c5994 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7e02a06b in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:429:20
    #8 0x55dd7df78ffb in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1523:26
    #9 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #10 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #11 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #12 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #13 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #14 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #15 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #16 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #17 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #18 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #19 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #20 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #21 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #22 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #23 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #24 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #25 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 13704 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bec4f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d404c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h92f11991e564882e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e02a01d in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:428:19
    #7 0x55dd7df78ffb in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1523:26
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 13704 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac9b2 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x55dd7e11e4ae in alloc::alloc::alloc_zeroed::ha0b2282220cb6b70 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:155:14
    #2 0x55dd7e11ed9f in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:43
    #3 0x55dd7e122a2e in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::ha915ea78757e6f79 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:231:9
    #4 0x55dd7e0bebbf in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::hd69b2f176b97a4ca /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:189:38
    #5 0x55dd7e0d5c3c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::h1c7f813946ef038c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:136:9
    #6 0x55dd7e158beb in alloc::vec::from_elem::h7e7e6738858c5994 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7e02a01d in regex::dfa::Cache::new::hbf0fcd4ffff8a416 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:428:19
    #8 0x55dd7df78ffb in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1523:26
    #9 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #10 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #11 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #12 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #13 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #14 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #15 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #16 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #17 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #18 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #19 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #20 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #21 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #22 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #23 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #24 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #25 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bb98f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h8b5b766b2f080c66 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d3e0c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h1ad4a2fb04867727 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e158899 in alloc::vec::from_elem::h1345301785a483c9 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7df78ffb in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1523:26
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e0bb98f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h8b5b766b2f080c66 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:188:45
    #5 0x55dd7e0d3e0c in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_in::h1ad4a2fb04867727 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:129:9
    #6 0x55dd7e158899 in alloc::vec::from_elem::h1345301785a483c9 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:1981:5
    #7 0x55dd7df78fab in regex::exec::ProgramCacheInner::new::h63a3a5b71eb9db68 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #8 0x55dd7df764f7 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::hcf90ca0807a3fa99 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #9 0x55dd7df45303 in core::ops::function::FnOnce::call_once::h019b0a04464ffd87 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #10 0x55dd7e1095c5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::h5381b1fb39102fa1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #11 0x55dd7dfe50c4 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::h19dcd9d8d587a0fc /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:216:44
    #12 0x55dd7dfe621d in thread_local::ThreadLocal$LT$T$GT$::get_or::he27beedf1d55e2eb /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:201:13
    #13 0x55dd7e12887a in regex::exec::Exec::searcher::h386c33eae7d0a225 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #14 0x55dd7e12887a in regex::exec::Exec::searcher_str::h4cb6ef8f90917ae0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #15 0x55dd7e12887a in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 312 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e26ccde in alloc::alloc::alloc::h80d9b1e399e6c2bd /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e26d041 in alloc::alloc::Global::alloc_impl::h35148cb3c8c60b33 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e282bd4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::hfed395b36809bc28 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e32d412 in alloc::raw_vec::finish_grow::h3a6f8decef16d639 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:490:9
    #5 0x55dd7e0cf9c5 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_amortized::h979e7daaeaac2a2c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:422:19
    #6 0x55dd7e0c0b19 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve::hd91b94199e146d4a /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:311:13
    #7 0x55dd7e155e67 in alloc::vec::Vec$LT$T$C$A$GT$::reserve::h91c385234e649b9e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:749:9
    #8 0x55dd7e160155 in _$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..iter..traits..collect..Extend$LT$T$GT$$GT$::extend::he33f483832b05e41 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:2150:9
    #9 0x55dd7e0385f4 in regex::dfa::Transitions::add::h698fe18672eaeee2 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1667:9
    #10 0x55dd7e034173 in regex::dfa::Fsm::add_state::h1d02f2fd5aee38f7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1480:24
    #11 0x55dd7e02e66e in regex::dfa::Fsm::cached_state::hec5fedc79615f690 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1175:9
    #12 0x55dd7e12bfd2 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1400:24
    #13 0x55dd7e12bfd2 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #14 0x55dd7e12bfd2 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #15 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #16 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #17 0x55dd7e12bfd2 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #18 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #19 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #20 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #21 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #22 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #23 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #24 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #25 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #26 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 116 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7df86f0b in hashbrown::raw::RawTable$LT$T$GT$::new_uninitialized::ha8cbdef9be9d37ad /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:411:38
    #3 0x55dd7df8832e in hashbrown::raw::RawTable$LT$T$GT$::fallible_with_capacity::h4bd602fc456cd95c /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:440:30
    #4 0x55dd7df8c5dd in hashbrown::raw::RawTable$LT$T$GT$::resize::h3c5c13d742891f9e /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:873:33
    #5 0x55dd7df8077e in hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h6cad1551e0d02141 /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:754:13
    #6 0x55dd7df8e952 in hashbrown::raw::RawTable$LT$T$GT$::reserve::ha63d0acc2ade1302 /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:707:16
    #7 0x55dd7df8bca9 in hashbrown::raw::RawTable$LT$T$GT$::insert::h785343dec3ccdbe4 /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:926:17
    #8 0x55dd7e06f0ba in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::insert::hdc944fcbabff5ce4 /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/map.rs:991:17
    #9 0x55dd7dfb567d in std::collections::hash::map::HashMap$LT$K$C$V$C$S$GT$::insert::h2cef9ec96d101721 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/collections/hash/map.rs:841:9
    #10 0x55dd7e037ef8 in regex::dfa::StateMap::insert::hac4290f8d63b2b90 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1635:9
    #11 0x55dd7e034f5a in regex::dfa::Fsm::add_state::h1d02f2fd5aee38f7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1500:9
    #12 0x55dd7e02e66e in regex::dfa::Fsm::cached_state::hec5fedc79615f690 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1175:9
    #13 0x55dd7e12bfd2 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1400:24
    #14 0x55dd7e12bfd2 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #15 0x55dd7e12bfd2 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #16 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #17 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #18 0x55dd7e12bfd2 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #19 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #20 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #21 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #22 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #23 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #24 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #25 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #26 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #27 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3acb59 in realloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:164:3
    #1 0x55dd7e26e399 in alloc::alloc::realloc::h0ea9e0aa7466f170 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:122:14
    #2 0x55dd7e26d9d3 in alloc::alloc::Global::grow_impl::hc5d583d840923f96 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:198:31
    #3 0x55dd7e282a22 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::grow::h6ce278680b1b9009 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:251:18
    #4 0x55dd7e32d67f in alloc::raw_vec::finish_grow::h3a6f8decef16d639 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:487:13
    #5 0x55dd7e347cec in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_amortized::hd802776c4e3c0ac0 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:422:19
    #6 0x55dd7e3345f9 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve::hfda7733610a858bd /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:311:13
    #7 0x55dd7e2ec5b7 in alloc::vec::Vec$LT$T$C$A$GT$::reserve::h7e9389d26d5287e3 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:749:9
    #8 0x55dd7e039a3d in regex::dfa::write_varu32::hff8cef6034523e2b /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1873:5
    #9 0x55dd7e02df69 in regex::dfa::Fsm::cached_state::hec5fedc79615f690 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1159:25
    #10 0x55dd7e12bfd2 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1400:24
    #11 0x55dd7e12bfd2 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #12 0x55dd7e12bfd2 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #13 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #14 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #15 0x55dd7e12bfd2 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #16 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #17 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #18 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #19 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #20 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #21 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #22 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #23 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #24 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e26ccde in alloc::alloc::alloc::h80d9b1e399e6c2bd /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e26d041 in alloc::alloc::Global::alloc_impl::h35148cb3c8c60b33 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e282bd4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::hfed395b36809bc28 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e32d412 in alloc::raw_vec::finish_grow::h3a6f8decef16d639 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:490:9
    #5 0x55dd7e0d2d45 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_amortized::hf920ef74f4b86427 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:422:19
    #6 0x55dd7e0c0439 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve::h66ef2443716208d6 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:311:13
    #7 0x55dd7e155fe7 in alloc::vec::Vec$LT$T$C$A$GT$::reserve::hb6c3f95c8f8764d6 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:749:9
    #8 0x55dd7e037f7f in regex::dfa::StateMap::insert::hac4290f8d63b2b90 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1636:9
    #9 0x55dd7e034f5a in regex::dfa::Fsm::add_state::h1d02f2fd5aee38f7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1500:9
    #10 0x55dd7e02e66e in regex::dfa::Fsm::cached_state::hec5fedc79615f690 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1175:9
    #11 0x55dd7e12bfd2 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1400:24
    #12 0x55dd7e12bfd2 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #13 0x55dd7e12bfd2 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #14 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #15 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #16 0x55dd7e12bfd2 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #17 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #18 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #19 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #20 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #21 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #22 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #23 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #24 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #25 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e26ccde in alloc::alloc::alloc::h80d9b1e399e6c2bd /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e26d041 in alloc::alloc::Global::alloc_impl::h35148cb3c8c60b33 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e282bd4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::hfed395b36809bc28 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e32d412 in alloc::raw_vec::finish_grow::h3a6f8decef16d639 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:490:9
    #5 0x55dd7e0cf9c5 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_amortized::h979e7daaeaac2a2c /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:422:19
    #6 0x55dd7e0c0b19 in alloc::raw_vec::RawVec$LT$T$C$A$GT$::try_reserve::hd91b94199e146d4a /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/raw_vec.rs:311:13
    #7 0x55dd7e155e67 in alloc::vec::Vec$LT$T$C$A$GT$::reserve::h91c385234e649b9e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/vec/mod.rs:749:9
    #8 0x55dd7e02d2ad in regex::dfa::Fsm::follow_epsilons::hfe741ba7caaa455c /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1064:9
    #9 0x55dd7e12bec5 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1395:9
    #10 0x55dd7e12bec5 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #11 0x55dd7e12bec5 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #12 0x55dd7e12bec5 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #13 0x55dd7e12bec5 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #14 0x55dd7e12bec5 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #15 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #16 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #17 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #18 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #19 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #20 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #21 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #22 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #23 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x55dd7d3ac83d in __interceptor_malloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x55dd7e11e9ce in alloc::alloc::alloc::ha9344170d49bdc68 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:86:14
    #2 0x55dd7e11ed31 in alloc::alloc::Global::alloc_impl::hf73abd4875d9d230 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:166:73
    #3 0x55dd7e1238a4 in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate::h8af1a0b7bf6a1b8f /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/alloc.rs:226:9
    #4 0x55dd7e06a22c in alloc::sync::Arc$LT$$u5b$T$u5d$$GT$::allocate_for_slice::_$u7b$$u7b$closure$u7d$$u7d$::h5dd827461ad5be86 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1166:26
    #5 0x55dd7e067283 in alloc::sync::Arc$LT$T$GT$::try_allocate_for_layout::he5f9d47ca3fbd9c1 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1111:19
    #6 0x55dd7e066904 in alloc::sync::Arc$LT$T$GT$::allocate_for_layout::he0b11f44bdd1b796 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1089:13
    #7 0x55dd7e06a032 in alloc::sync::Arc$LT$$u5b$T$u5d$$GT$::allocate_for_slice::hea2c76653066b3fa /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1164:13
    #8 0x55dd7e069d9e in alloc::sync::Arc$LT$$u5b$T$u5d$$GT$::copy_from_slice::h8d6d55a33aaf0d86 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1190:23
    #9 0x55dd7e06cba6 in _$LT$alloc..sync..Arc$LT$$u5b$T$u5d$$GT$$u20$as$u20$alloc..sync..ArcFromSlice$LT$T$GT$$GT$::from_slice::ha65430b14b52840e /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:1262:18
    #10 0x55dd7e06cd56 in _$LT$alloc..sync..Arc$LT$$u5b$T$u5d$$GT$$u20$as$u20$core..convert..From$LT$$RF$$u5b$T$u5d$$GT$$GT$::from::hf0ea320a7fb91f47 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/alloc/src/sync.rs:2299:9
    #11 0x55dd7e02f33e in regex::dfa::Fsm::cached_state_key::hc4922cfad6faacff /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1238:32
    #12 0x55dd7e02df69 in regex::dfa::Fsm::cached_state::hec5fedc79615f690 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1159:25
    #13 0x55dd7e12bfd2 in regex::dfa::Fsm::start_state::hd2686bcdee336dce /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:1400:24
    #14 0x55dd7e12bfd2 in regex::dfa::Fsm::forward::h20928174cb15f9bf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:467:19
    #15 0x55dd7e12bfd2 in regex::exec::ExecNoSync::shortest_dfa::h35fbb5c9eb947a36 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:790:9
    #16 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h9f541d424f972555 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:442:23
    #17 0x55dd7e12bfd2 in _$LT$regex..exec..ExecNoSyncStr$u20$as$u20$regex..re_trait..RegularExpression$GT$::shortest_match_at::h5b609e5156e05cd7 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:390:9
    #18 0x55dd7e12bfd2 in regex::re_unicode::Regex::shortest_match_at::h44d6a8dee3f5aee4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #19 0x55dd7e14565c in regex::re_unicode::Regex::is_match_at::h5a8f9b3e93c04233 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #20 0x55dd7e126f48 in regex::re_unicode::Regex::is_match::h90060614d7d8aa52 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #21 0x55dd7d5d730b in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::hc27833e617d4c027 /home/capsule/core/src/config.rs:228:16
    #22 0x55dd7d958977 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h5a4b62cc1f825739 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/slice/iter/macros.rs:203:21
    #23 0x55dd7d5d68c8 in capsule::config::RuntimeConfig::to_eal_args::he3e6ea5ac107575a /home/capsule/core/src/config.rs:227:9
    #24 0x55dd7d61d58f in capsule::runtime::Runtime::build::h69d2790a5f0f765c /home/capsule/core/src/runtime/mod.rs:83:24
    #25 0x55dd7d3f9580 in ping4d::main::h030afa5f0e6e20be /home/capsule/examples/ping4d/main.rs:69:5
    #26 0x55dd7d40c29a in core::ops::function::FnOnce::call_once::h1aa1293e38e47904 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/core/src/ops/function.rs:227:5
    #27 0x55dd7d3ed356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hbf2306c09299a156 /rustc/17eec1433c69972844dd228b5fe801f218e118c3/library/std/src/rt.rs:66:18
```

File: ffi/build.rs [hunk 1]
```diff
@@ -171,6 +171,7 @@ const RTE_DEPS_LIBS: &[&str] = &["numa", "pcap"];
 fn bind(path: &Path) {
     cc::Build::new()
         .file("src/shim.c")
+        .flag("-mavx")
```
Comment (drunkirishcoder) [inline ffi/build.rs:174]: is this the same as `-march=corei7-avx`?

**Review by drunkirishcoder — APPROVED** [review]
one very minor question. otherwise 👍 to the upgrades.

**Comment by drunkirishcoder** [comment]
Unfortunately I can get the leak locally when run sanitize

```
==1==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 14800 byte(s) in 1 object(s) allocated from:
    #0 0x5627eb8699b2 in calloc /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5627ed43e492 in std::sys::unix::alloc::_$LT$impl$u20$core..alloc..global..GlobalAlloc$u20$for$u20$std..alloc..System$GT$::alloc_zeroed::hf2e5450ed24e07d5 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/alloc.rs:30:13
    #2 0x5627ed34ee61 in __rdl_alloc_zeroed /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/alloc.rs:389:13
    #3 0x5627ed697c8e in alloc::alloc::alloc_zeroed::h349220cdf19925ff /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:155:14
    #4 0x5627ed698181 in alloc::alloc::Global::alloc_impl::h172b392325a9d90a /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:166:43
    #5 0x5627ed69898e in _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::allocate_zeroed::h2f0f76a495808b52 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:231:9
    #6 0x5627ed68e55f in alloc::raw_vec::RawVec$LT$T$C$A$GT$::allocate_in::h2e5173a6bcdf962b /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:202:38
    #7 0x5627ed6906bc in alloc::raw_vec::RawVec$LT$T$C$A$GT$::with_capacity_zeroed_in::h702bb409ca746485 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/raw_vec.rs:149:9
    #8 0x5627ed69d70b in alloc::vec::from_elem::hcd066c6053c4e9e8 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1992:5
    #9 0x5627ec4a44ad in regex::dfa::Cache::new::h58305275f216d018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/dfa.rs:428:19
    #10 0x5627ec4ceb0b in regex::exec::ProgramCacheInner::new::h02aeb94e37b296d1 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1521:18
    #11 0x5627ec4cc057 in regex::exec::Exec::searcher::_$u7b$$u7b$closure$u7d$$u7d$::h72b0231977c6fc42 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1257:38
    #12 0x5627ec4e3043 in core::ops::function::FnOnce::call_once::h054899bb56aecdb6 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    #13 0x5627ec5b79a5 in regex::cache::imp::Cached$LT$T$GT$::get_or::_$u7b$$u7b$closure$u7d$$u7d$::he9b7b38dd1e2a2f0 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/cache.rs:29:42
    #14 0x5627ec47e024 in thread_local::ThreadLocal$LT$T$GT$::get_or_try::heef8b078a10cacee /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.2/src/lib.rs:215:44
    #15 0x5627ec47f17d in thread_local::ThreadLocal$LT$T$GT$::get_or::h7bce3fbe2915425c /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.2/src/lib.rs:200:13
    #16 0x5627ec5f1cfa in regex::exec::Exec::searcher::h50891b99118b4fbf /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1260:20
    #17 0x5627ec5f1cfa in regex::exec::Exec::searcher_str::h15f01daef785f46f /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/exec.rs:1267:23
    #18 0x5627ec5f1cfa in regex::re_unicode::Regex::shortest_match_at::h25664feece19a7c4 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:630:9
    #19 0x5627ec60ea8c in regex::re_unicode::Regex::is_match_at::h2c76c62d00e43812 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:640:9
    #20 0x5627ec5f03c8 in regex::re_unicode::Regex::is_match::h31cf0811c2f9007c /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.4.3/src/re_unicode.rs:199:9
    #21 0x5627ebac06db in capsule::config::RuntimeConfig::to_eal_args::_$u7b$$u7b$closure$u7d$$u7d$::h96cd10e322f32b8e /home/capsule/core/src/config.rs:228:16
    #22 0x5627ebb300b7 in _$LT$core..slice..iter..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::for_each::h91f3ed6ad06827ab /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/iter/macros.rs:203:21
    #23 0x5627ebabfc98 in capsule::config::RuntimeConfig::to_eal_args::h1d77469b579a0ef4 /home/capsule/core/src/config.rs:227:9
    #24 0x5627eba90716 in capsule::runtime::Runtime::build::hb34fff4cc838efd4 /home/capsule/core/src/runtime/mod.rs:83:24
    #25 0x5627eb8bc047 in ping4d::main::h4834f4bf2616c938 /home/capsule/examples/ping4d/main.rs:69:5
    #26 0x5627eb89fb6a in core::ops::function::FnOnce::call_once::hc21ca62c6c550c7e /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    #27 0x5627eb8ae356 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hd24c33359b817f8e /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
    #28 0x5627ed40446e in std::panicking::try::do_call::hfd507d42569725ca /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
    #29 0x5627ed408e2c in __rust_try (/home/capsule/target/x86_64-unknown-linux-gnu/debug/ping4d+0x1e7ae2c)
    #30 0x5627ed34a394 in std::panic::catch_unwind::h95372c25788ee9a9 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
    #31 0x5627ed59b463 in std::rt::lang_start_internal::hfec13698668c68e8 /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:51:25
```

Looks like we run into this issue, https://github.com/rust-lang/regex/issues/739. Finger was pointed at `ThreadLocal` via `Regex`. But they closed the issue and the trail has gone cold.
